-- PostgreSQL para o plano Free do Render. Executar novamente preserva os dados.
-- O banco já é criado pelo Render; este arquivo cria somente sua estrutura.
CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  senha_hash VARCHAR(255) NOT NULL,
  tipo VARCHAR(20) NOT NULL DEFAULT 'operador' CHECK (tipo IN ('administrador', 'operador')),
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS veiculos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  placa VARCHAR(15) NOT NULL UNIQUE,
  capacidade_kg NUMERIC(10,2) NOT NULL CHECK (capacidade_kg > 0),
  status VARCHAR(20) NOT NULL DEFAULT 'disponivel' CHECK (status IN ('disponivel', 'manutencao')),
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rotas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL UNIQUE,
  origem VARCHAR(150) NOT NULL,
  destino VARCHAR(150) NOT NULL,
  distancia_km NUMERIC(10,2) NOT NULL CHECK (distancia_km > 0),
  pontos JSON NOT NULL,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS entregas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(200) NOT NULL,
  origem VARCHAR(150) NOT NULL,
  destino VARCHAR(150) NOT NULL,
  peso_kg NUMERIC(10,2) NOT NULL CHECK (peso_kg > 0),
  prazo_min NUMERIC(10,2) NOT NULL CHECK (prazo_min > 0),
  data_agendada DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pendente'
    CHECK (status IN ('pendente', 'em_andamento', 'concluida', 'cancelada')),
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  veiculo_id INTEGER NOT NULL REFERENCES veiculos(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  rota_id INTEGER REFERENCES rotas(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_entrega_inicio CHECK (status <> 'em_andamento' OR rota_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS simulacoes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entrega_id INTEGER NOT NULL REFERENCES entregas(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  cenario VARCHAR(20) NOT NULL CHECK (cenario IN ('normal', 'lento')),
  velocidade_kmh INTEGER NOT NULL CHECK (velocidade_kmh IN (20,30)),
  prazo_min NUMERIC(10,2) NOT NULL CHECK (prazo_min > 0),
  rota_id INTEGER NOT NULL REFERENCES rotas(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  resultados JSON NOT NULL,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  atualizado_por_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_usuario_email_ci ON usuarios (LOWER(email));
CREATE UNIQUE INDEX IF NOT EXISTS uk_veiculo_placa_ci ON veiculos (LOWER(placa));
CREATE UNIQUE INDEX IF NOT EXISTS uk_rota_nome_ci ON rotas (LOWER(nome));
CREATE INDEX IF NOT EXISTS idx_rota_origem_destino ON rotas (origem, destino);
CREATE INDEX IF NOT EXISTS idx_entrega_status ON entregas (status);
CREATE INDEX IF NOT EXISTS idx_entrega_data ON entregas (data_agendada);
CREATE INDEX IF NOT EXISTS idx_entrega_veiculo_status ON entregas (veiculo_id, status);
CREATE INDEX IF NOT EXISTS idx_entrega_usuario ON entregas (usuario_id);
CREATE INDEX IF NOT EXISTS idx_entrega_rota ON entregas (rota_id);
CREATE INDEX IF NOT EXISTS idx_simulacao_entrega_data ON simulacoes (entrega_id, "updatedAt");
CREATE INDEX IF NOT EXISTS idx_simulacao_rota ON simulacoes (rota_id);
CREATE INDEX IF NOT EXISTS idx_simulacao_usuario ON simulacoes (usuario_id);
CREATE INDEX IF NOT EXISTS idx_simulacao_atualizador ON simulacoes (atualizado_por_id);
